# Generated by Django 5.0.6 on 2024-05-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_warehouseitem_date_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseitem',
            name='part_type',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='warehouseitem',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='warehouseitem',
            name='manufacturer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='warehouseitem',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='warehouseitem',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='warehouseitem',
            name='part_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='warehouseitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
