# Generated by Django 5.0.6 on 2024-05-23 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_warehouseitem_part_type_alter_warehouseitem_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseitem',
            name='part_type',
        ),
    ]
