# Generated by Django 5.0.6 on 2024-05-25 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_warehouseitem_part_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WarehouseItem',
            new_name='main_WarehouseItem',
        ),
    ]
