# Generated by Django 5.0.6 on 2024-05-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_warehouseitem_main_warehouseitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('availability', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='main_WarehouseItem',
        ),
    ]
