# Generated by Django 5.0.6 on 2024-05-31 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_item_delete_main_warehouseitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrakeParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.BooleanField(default=True)),
                ('article', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('part_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarBodyParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.BooleanField(default=True)),
                ('article', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('part_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ChassisParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.BooleanField(default=True)),
                ('article', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('part_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClimateParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.BooleanField(default=True)),
                ('article', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('part_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ElectricityParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.BooleanField(default=True)),
                ('article', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('part_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EngineParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.BooleanField(default=True)),
                ('article', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('part_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InteriorParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.BooleanField(default=True)),
                ('article', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('part_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LiquidsParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.BooleanField(default=True)),
                ('article', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('part_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.BooleanField(default=True)),
                ('article', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('part_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PneumaticParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.BooleanField(default=True)),
                ('article', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('part_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SteeringParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.BooleanField(default=True)),
                ('article', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('part_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TransmissionParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.BooleanField(default=True)),
                ('article', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('part_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='item',
            old_name='part_number',
            new_name='article',
        ),
        migrations.AddField(
            model_name='item',
            name='part_type',
            field=models.CharField(default='UNKNOWN', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='availability',
            field=models.BooleanField(choices=[(True, 'In Stock'), (False, 'Out of Stock')], default=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='Brake_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.brakeparts'),
        ),
        migrations.AddField(
            model_name='item',
            name='CarBodyParts_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.carbodyparts'),
        ),
        migrations.AddField(
            model_name='item',
            name='chassis_parts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.chassisparts'),
        ),
        migrations.AddField(
            model_name='item',
            name='Climate_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.climateparts'),
        ),
        migrations.AddField(
            model_name='item',
            name='Electricity_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.electricityparts'),
        ),
        migrations.AddField(
            model_name='item',
            name='engine_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.engineparts'),
        ),
        migrations.AddField(
            model_name='item',
            name='Interior_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.interiorparts'),
        ),
        migrations.AddField(
            model_name='item',
            name='Liquids_Parts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.liquidsparts'),
        ),
        migrations.AddField(
            model_name='item',
            name='Maintenance_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.maintenanceparts'),
        ),
        migrations.AddField(
            model_name='item',
            name='pneumatic_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pneumaticparts'),
        ),
        migrations.AddField(
            model_name='item',
            name='Steering_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.steeringparts'),
        ),
        migrations.AddField(
            model_name='item',
            name='transmission_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.transmissionparts'),
        ),
    ]
