# Generated by Django 5.0.6 on 2024-06-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_brake_part_item_brake_part_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='availability',
            field=models.CharField(blank=True, default='green', max_length=10),
        ),
    ]
