# Generated by Django 5.0.6 on 2024-06-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_item_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
