# Generated by Django 5.0.6 on 2024-07-29 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_brand_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('vin_code', models.CharField(max_length=17, primary_key=True, serialize=False, unique=True)),
                ('engine_number', models.CharField(max_length=100)),
                ('engine_volume', models.DecimalField(decimal_places=2, max_digits=5)),
                ('year_of_manufacture', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('gearbox_type', models.CharField(max_length=50)),
                ('state_number', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DriverComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('complaint_text', models.TextField()),
                ('vin_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.car')),
            ],
        ),
        migrations.CreateModel(
            name='Fault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('criticality', models.CharField(max_length=50)),
                ('mileage', models.IntegerField()),
                ('vin_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.car')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('recommendation', models.TextField()),
                ('vin_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.car')),
            ],
        ),
        migrations.CreateModel(
            name='WorkPerformed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mileage', models.IntegerField()),
                ('work_name', models.CharField(max_length=255)),
                ('used_parts', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('article', models.CharField(max_length=100)),
                ('vin_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.car')),
            ],
        ),
    ]
