# Generated by Django 5.0.6 on 2024-07-29 13:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_car_drivercomplaint_fault_recommendation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workperformed',
            name='article',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workperformed',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
