# Generated by Django 5.0.6 on 2024-08-05 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_workperformed_article_alter_workperformed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mileage', models.IntegerField()),
                ('description', models.TextField()),
                ('part_article', models.CharField(blank=True, max_length=100, null=True)),
                ('part_name', models.CharField(blank=True, max_length=100, null=True)),
                ('part_manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.car')),
            ],
        ),
    ]
